import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { joinedRoomPreview, RoomPreviewDetails } from '../ride/JoinedRoom';

type PublicUser = { userId: string; displayName: string; username?: string; id?: string };
type Request = { id: string; userId: string; displayName: string; username?: string };
type RideInvitation = { id: string; room_id: string; inviter_name?: string; destination_label?: string };
const COLORS={ink:'#0B130E',card:'#142318',line:'#1E3A28',text:'#F0FDF4',muted:'#A3B8A8',green:'#16A34A',red:'#DC2626',blue:'#2F80ED',input:'#0F1A12'};

export default function FriendsScreen({ apiBaseUrl, authToken, onBack, onConfirmJoin, refreshSignal = 0 }: {apiBaseUrl:string;authToken:string;onBack:()=>void;onConfirmJoin:(room:RoomPreviewDetails)=>void | Promise<void>;refreshSignal?:number}) {
 const [friends,setFriends]=useState<PublicUser[]>([]),[incoming,setIncoming]=useState<Request[]>([]),[outgoing,setOutgoing]=useState<Request[]>([]),[rides,setRides]=useState<RideInvitation[]>([]),[query,setQuery]=useState(''),[results,setResults]=useState<PublicUser[]>([]),[username,setUsername]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const acceptingRef = useRef(false);
 const [accepting, setAccepting] = useState(false);
 const consumedInvites = useRef(new Set<string>());
 const request=useCallback(async (path:string, options:RequestInit={})=>{const r=await fetch(`${apiBaseUrl}/api${path}`,{...options,headers:{Authorization:`Bearer ${authToken}`,'Content-Type':'application/json',...(options.headers||{})}});const body=await r.json().catch(()=>null);if(!r.ok)throw new Error(body?.error||'Unable to complete this action');return body;},[apiBaseUrl,authToken]);
 const refresh=useCallback(async()=>{setLoading(true);setError('');try{const [f,i,o,r]=await Promise.all([request('/friends'),request('/friends/requests/incoming'),request('/friends/requests/outgoing'),request('/ride-invitations')]);setFriends(f);setIncoming(i);setOutgoing(o);setRides(r.filter((invite:RideInvitation)=>!consumedInvites.current.has(invite.id)));}catch(e:any){setError(e.message);}finally{setLoading(false);}},[request]);
 useEffect(()=>{void refresh();},[refresh, refreshSignal]);
 const act=async(path:string,method='POST',body?:object)=>{try{await request(path,{method,body:body?JSON.stringify(body):undefined});await refresh();}catch(e:any){Alert.alert('Friends',e.message);}};
 const acceptRide=async(id:string)=>{
   if(acceptingRef.current)return;
   acceptingRef.current=true;setAccepting(true);
   try {
     const room=await request(`/ride-invitations/${id}/accept`,{method:'POST'});
     const preview=joinedRoomPreview(room);
     await onConfirmJoin(preview);
     consumedInvites.current.add(id);
     setRides(current=>current.filter(invite=>invite.id!==id));
   } catch(e:any) { Alert.alert('Ride invitation',e.message || 'Unable to open this ride. Please try again.'); }
   finally {acceptingRef.current=false;setAccepting(false);}
 };
 const search=async()=>{try{setResults(await request(`/users/search?q=${encodeURIComponent(query)}`));}catch(e:any){setError(e.message);}};
 return <SafeAreaView style={s.shell}><ScrollView contentContainerStyle={s.content}><Pressable onPress={onBack}><Text style={s.back}>← Back</Text></Pressable><View style={s.head}><Text style={s.eyebrow}>TRUSTED COORDINATION</Text><Text style={s.title}>Friends</Text><Text style={s.copy}>Friends never receive your location or safety information automatically.</Text></View>
 <View style={s.card}><Text style={s.cardTitle}>Your username</Text><Text style={s.copy}>Choose the public handle riders use to find you. Email stays private.</Text><View style={s.row}><TextInput value={username} onChangeText={setUsername} placeholder="e.g. sanjiban" placeholderTextColor={COLORS.muted} style={s.input}/><Pressable style={s.small} onPress={()=>act('/users/username','PUT',{username})}><Text style={s.smallText}>Save</Text></Pressable></View></View>
 <View style={s.card}><Text style={s.cardTitle}>Find riders</Text><View style={s.row}><TextInput value={query} onChangeText={setQuery} autoCapitalize="none" placeholder="Username (3+ characters)" placeholderTextColor={COLORS.muted} style={s.input}/><Pressable style={s.small} onPress={search}><Text style={s.smallText}>Search</Text></Pressable></View>{results.map(u=><View key={u.userId} style={s.person}><Text style={s.name}>{u.displayName} <Text style={s.handle}>@{u.username}</Text></Text><Pressable onPress={()=>act('/friends/requests','POST',{receiver_user_id:u.userId})}><Text style={s.link}>Add</Text></Pressable></View>)}</View>
 <View style={s.card}><Text style={s.cardTitle}>Friends</Text>{loading?<Text style={s.copy}>Loading…</Text>:friends.length===0?<Text style={s.copy}>No friends yet. Search by username to coordinate rides.</Text>:friends.map(u=><View key={u.userId} style={s.person}><Text style={s.name}>{u.displayName} <Text style={s.handle}>@{u.username}</Text></Text><View style={s.actionRow}><Pressable onPress={()=>act(`/friends/${u.userId}`,'DELETE')}><Text style={s.link}>Remove</Text></Pressable><Pressable onPress={()=>Alert.alert('Block rider','This removes the friendship and prevents future friend requests and invitations.',[{text:'Cancel'},{text:'Block',style:'destructive',onPress:()=>act(`/users/${u.userId}/block`)}])}><Text style={s.danger}>Block</Text></Pressable></View></View>)}</View>
 <View style={s.card}><Text style={s.cardTitle}>Requests</Text>{incoming.map(r=><View key={r.id} style={s.person}><Text style={s.name}>{r.displayName} <Text style={s.handle}>@{r.username}</Text></Text><View style={s.actionRow}><Pressable onPress={()=>act(`/friends/requests/${r.id}/accept`)}><Text style={s.link}>Accept</Text></Pressable><Pressable onPress={()=>act(`/friends/requests/${r.id}/decline`)}><Text style={s.danger}>Decline</Text></Pressable></View></View>)}{outgoing.map(r=><View key={r.id} style={s.person}><Text style={s.name}>{r.displayName} <Text style={s.handle}>@{r.username} · Pending</Text></Text><Pressable onPress={()=>act(`/friends/requests/${r.id}`,'DELETE')}><Text style={s.link}>Cancel</Text></Pressable></View>)}{!incoming.length&&!outgoing.length&&<Text style={s.copy}>No pending friend requests.</Text>}</View>
 <View style={s.card}><Text style={s.cardTitle}>Ride invitations</Text>{rides.map(i=><View key={i.id} style={s.person}><Text style={s.name}>{i.inviter_name||'A friend'} invited you to {i.destination_label||'a ride'}</Text><View style={s.actionRow}><Pressable testID={`accept-ride-${i.id}`} disabled={accepting} onPress={()=>acceptRide(i.id)}><Text style={s.link}>Join ride</Text></Pressable><Pressable disabled={accepting} onPress={()=>act(`/ride-invitations/${i.id}/decline`)}><Text style={s.danger}>Decline</Text></Pressable></View></View>)}{!rides.length&&<Text style={s.copy}>No incoming ride invitations.</Text>}</View>
 {error?<Text style={s.error}>{error}</Text>:null}<Pressable style={s.refresh} onPress={refresh}><Text style={s.smallText}>Refresh</Text></Pressable></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({shell:{flex:1,backgroundColor:COLORS.ink},content:{padding:20,gap:14},back:{color:COLORS.blue,fontWeight:'700'},head:{gap:5},eyebrow:{color:'#86EFAC',fontSize:11,fontWeight:'800',letterSpacing:1},title:{color:COLORS.text,fontSize:28,fontWeight:'900'},copy:{color:COLORS.muted,fontSize:12,lineHeight:17},card:{backgroundColor:COLORS.card,borderColor:COLORS.line,borderWidth:1,borderRadius:14,padding:15,gap:10},cardTitle:{color:COLORS.text,fontSize:16,fontWeight:'800'},row:{flexDirection:'row',gap:8},input:{flex:1,backgroundColor:COLORS.input,borderColor:COLORS.line,borderWidth:1,borderRadius:10,color:COLORS.text,paddingHorizontal:11,height:42},small:{backgroundColor:COLORS.green,borderRadius:10,paddingHorizontal:12,justifyContent:'center'},smallText:{color:COLORS.ink,fontWeight:'900'},person:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,borderTopColor:COLORS.line,borderTopWidth:1,paddingTop:10},name:{flex:1,color:COLORS.text,fontWeight:'700'},handle:{color:COLORS.muted,fontWeight:'400'},actionRow:{flexDirection:'row',gap:12},link:{color:'#60A5FA',fontWeight:'800'},danger:{color:'#F87171',fontWeight:'800'},error:{color:'#FCA5A5'},refresh:{alignSelf:'center',backgroundColor:COLORS.green,borderRadius:10,padding:12}});
