import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

type Friend={userId:string;displayName:string;username?:string};
const C={card:'#142318',line:'#1E3A28',text:'#F0FDF4',muted:'#A3B8A8',green:'#16A34A',ink:'#0B130E',blue:'#60A5FA',red:'#F87171'};
export default function FriendInvitePicker({apiBaseUrl,authToken,roomId}:{apiBaseUrl:string;authToken:string;roomId:string}) {
 const [open,setOpen]=useState(false),[friends,setFriends]=useState<Friend[]>([]),[selected,setSelected]=useState<string[]>([]),[loading,setLoading]=useState(false),[sending,setSending]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!open)return;setLoading(true);fetch(`${apiBaseUrl}/api/friends`,{headers:{Authorization:`Bearer ${authToken}`}}).then(async r=>{const b=await r.json();if(!r.ok)throw new Error(b.error);setFriends(b);}).catch(e=>setMessage(e.message||'Unable to load friends')).finally(()=>setLoading(false));},[open,apiBaseUrl,authToken]);
 const send=async()=>{setSending(true);setMessage('');const failed:string[]=[];for(const userId of selected){try{const r=await fetch(`${apiBaseUrl}/api/rooms/${roomId}/invitations`,{method:'POST',headers:{Authorization:`Bearer ${authToken}`,'Content-Type':'application/json'},body:JSON.stringify({invitee_user_id:userId})});if(!r.ok)failed.push(userId);}catch{failed.push(userId);}}setSelected([]);setSending(false);setMessage(failed.length?`${selected.length-failed.length} sent; ${failed.length} could not be sent.`:`${selected.length} invitation${selected.length===1?'':'s'} sent.`);};
 if(!open)return <Pressable onPress={()=>setOpen(true)} style={s.open}><Text style={s.openText}>Invite Friends</Text></Pressable>;
 return <View style={s.card}><View style={s.header}><Text style={s.title}>Invite Friends</Text><Pressable onPress={()=>setOpen(false)}><Text style={s.close}>Close</Text></Pressable></View>{loading?<Text style={s.copy}>Loading friends…</Text>:friends.length===0?<Text style={s.copy}>No friends yet. Share the room code as a fallback.</Text>:friends.map(friend=>{const active=selected.includes(friend.userId);return <Pressable key={friend.userId} onPress={()=>setSelected(v=>active?v.filter(id=>id!==friend.userId):[...v,friend.userId])} style={s.friend}><Text style={s.name}>{active?'☑':'☐'} {friend.displayName} <Text style={s.handle}>@{friend.username}</Text></Text></Pressable>;})}{message?<Text style={message.includes('could not')?s.error:s.copy}>{message}</Text>:null}<Pressable disabled={!selected.length||sending} onPress={send} style={[s.send,(!selected.length||sending)&&s.disabled]}><Text style={s.sendText}>{sending?'Sending…':`Send Invitations${selected.length?` (${selected.length})`:''}`}</Text></Pressable></View>;
}
const s=StyleSheet.create({open:{backgroundColor:'#0F2918',borderColor:C.green,borderWidth:1,borderRadius:10,padding:12,alignItems:'center',marginBottom:10},openText:{color:C.green,fontWeight:'900'},card:{backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:12,padding:12,gap:9,marginBottom:10},header:{flexDirection:'row',justifyContent:'space-between'},title:{color:C.text,fontWeight:'800',fontSize:15},close:{color:C.blue,fontWeight:'700'},copy:{color:C.muted,fontSize:12},friend:{paddingVertical:6},name:{color:C.text,fontWeight:'700'},handle:{color:C.muted,fontWeight:'400'},send:{backgroundColor:C.green,borderRadius:10,padding:12,alignItems:'center'},disabled:{opacity:.5},sendText:{color:C.ink,fontWeight:'900'},error:{color:C.red,fontSize:12}});
