import React, { useEffect, useState } from 'react';
import { Alert, Pressable, Share, StyleSheet, Text, View } from 'react-native';

interface Props { apiBaseUrl: string; authToken: string; groupCode: string; }

export default function GuardianPortalControls({ apiBaseUrl, authToken, groupCode }: Props) {
  const [loading, setLoading] = useState(false);
  const [active, setActive] = useState(false);
  const [url, setUrl] = useState<string | null>(null);
  useEffect(() => { let cancelled = false; fetch(`${apiBaseUrl}/api/guardian-portal/shares/current?group_code=${encodeURIComponent(groupCode)}`, { headers: { Authorization: `Bearer ${authToken}` } }).then(response => response.ok ? response.json() : null).then(body => { if (!cancelled) setActive(body?.active === true); }).catch(() => undefined); return () => { cancelled = true; }; }, [apiBaseUrl, authToken, groupCode]);
  const create = async () => { setLoading(true); try { const response = await fetch(`${apiBaseUrl}/api/guardian-portal/shares`, { method: 'POST', headers: { Authorization: `Bearer ${authToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ group_code: groupCode }) }); const body = await response.json(); if (!response.ok || typeof body?.url !== 'string') throw new Error('Share creation failed'); setUrl(body.url); setActive(true); await Share.share({ title: 'Guardian Portal', message: `Follow my live ride in Guardian Portal: ${body.url}` }); } catch { Alert.alert('Guardian Portal', 'Could not start live sharing. Please try again.'); } finally { setLoading(false); } };
  const revoke = async () => { setLoading(true); try { const response = await fetch(`${apiBaseUrl}/api/guardian-portal/shares/current?group_code=${encodeURIComponent(groupCode)}`, { method: 'DELETE', headers: { Authorization: `Bearer ${authToken}` } }); if (!response.ok) throw new Error('Share revocation failed'); setActive(false); setUrl(null); } catch { Alert.alert('Guardian Portal', 'Could not stop live sharing. Please try again.'); } finally { setLoading(false); } };
  return <View style={styles.card}><View><Text style={styles.title}>Guardian Portal</Text><Text style={styles.copy}>{active ? 'Live ride sharing is active.' : 'Share a private live ride link with your guardian.'}</Text></View>{active && url ? <Pressable accessibilityRole="button" accessibilityLabel="Share live ride link" onPress={() => Share.share({ title: 'Guardian Portal', message: `Follow my live ride in Guardian Portal: ${url}` })} style={styles.linkButton}><Text style={styles.linkButtonText}>Share live link</Text></Pressable> : null}<Pressable accessibilityRole="button" disabled={loading} onPress={active ? revoke : create} style={[styles.actionButton, active ? styles.stopButton : styles.startButton, loading && styles.disabled]}><Text style={styles.actionButtonText}>{loading ? 'Please wait…' : active ? 'Stop sharing' : 'Share live ride'}</Text></Pressable></View>;
}

const styles = StyleSheet.create({
  card: { backgroundColor: '#142318', borderColor: '#1E3A28', borderWidth: 1, borderRadius: 16, padding: 16, gap: 12 }, title: { color: '#F0FDF4', fontSize: 17, fontWeight: '800' }, copy: { color: '#A3B8A8', fontSize: 12, lineHeight: 17, marginTop: 3 }, actionButton: { minHeight: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 }, startButton: { backgroundColor: '#16A34A' }, stopButton: { backgroundColor: '#7F1D1D' }, actionButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' }, linkButton: { minHeight: 44, alignItems: 'center', justifyContent: 'center', borderRadius: 12, borderColor: '#1E3A28', borderWidth: 1 }, linkButtonText: { color: '#F0FDF4', fontWeight: '800', fontSize: 14 }, disabled: { opacity: 0.6 },
});
