import { useEffect, useMemo, useRef, useState } from 'react';
import { API_BASE_URL } from '../config/env';
export interface Weather { condition: string; temperatureC?: number | null; precipitationProbability?: number | null; windSpeedKmh?: number | null; fetchedAt: string; }
export interface Advisory { id: string; type?: string; context?: 'current' | 'ahead' | 'destination' | 'start'; severity: 'info' | 'warning'; title: string; message: string; }
export type WeatherFailureReason = 'no_location_data' | 'provider_timeout' | 'provider_unavailable' | 'network_error' | 'partial_failure' | 'unknown';
export interface WeatherSafety { current: Weather | null; destination: Weather | null; advisories: Advisory[]; reason?: WeatherFailureReason; }
export interface WeatherSafetyState { data: WeatherSafety | null; isLoading: boolean; isRefreshing: boolean; isStale: boolean; errorReason?: WeatherFailureReason; }
type Point = { latitude: number; longitude: number };
const routeSamples = (points: Point[], destination: Point | null) => { const source = points.length ? points : destination ? [destination] : []; return [...new Set([0, .25, .5, .75, 1].map(x => Math.round((source.length - 1) * x)))].map(i => ({ location: source[i], progress: source.length > 1 ? i / (source.length - 1) : 1 })); };
export function useWeatherSafety(groupCode: string, token: string, start: Point | null, destination: Point | null, route: Point[], enabled: boolean, onAdvisory?: (item: Advisory, snapshotKey: string) => void, routeVersion?: number) {
  const [state, setState] = useState<WeatherSafetyState>({ data: null, isLoading: true, isRefreshing: false, isStale: false }); const requestId = useRef(0);
  const signature = useMemo(() => `${start?.latitude.toFixed(2)}:${start?.longitude.toFixed(2)}:${destination?.latitude.toFixed(2)}:${destination?.longitude.toFixed(2)}:${routeVersion ?? 0}`, [start?.latitude, start?.longitude, destination?.latitude, destination?.longitude, routeVersion]);
  useEffect(() => { if (!enabled || !token || !groupCode) return; let alive = true; const seen = new Set<string>(); const currentRequest = ++requestId.current;
    const load = async () => { setState(previous => ({ ...previous, isLoading: previous.data === null, isRefreshing: previous.data !== null })); try { const r = await fetch(`${API_BASE_URL}/api/rooms/${groupCode}/weather/safety`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ start, destination, route: routeSamples(route, destination) }) }); if (!r.ok) throw new Error('weather request failed'); const next = await r.json() as WeatherSafety; if (!alive || currentRequest !== requestId.current) return; const hasWeather = next.current !== null || next.destination !== null || next.advisories.length > 0; setState(previous => hasWeather || previous.data === null ? { data: next, isLoading: false, isRefreshing: false, isStale: false, errorReason: next.reason } : { ...previous, isLoading: false, isRefreshing: false, isStale: true, errorReason: next.reason ?? 'provider_unavailable' }); next.advisories.forEach(x => { const key = `${x.type ?? x.title}:${signature}`; if (!seen.has(key)) { seen.add(key); onAdvisory?.(x, signature); } }); } catch { if (alive && currentRequest === requestId.current) setState(previous => previous.data ? { ...previous, isLoading: false, isRefreshing: false, isStale: true, errorReason: 'network_error' } : { data: null, isLoading: false, isRefreshing: false, isStale: false, errorReason: 'network_error' }); } };
    load(); const timer = setInterval(load, 15 * 60 * 1000); return () => { alive = false; clearInterval(timer); };
  }, [groupCode, token, enabled, signature, onAdvisory]); return state;
}
