import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { MapContainer, Marker, TileLayer, useMap } from 'react-leaflet';
import { io } from 'socket.io-client';
import 'leaflet/dist/leaflet.css'; import './styles.css';

type Location={latitude:number;longitude:number;lastUpdatedAt:number|null;connectionState:'CONNECTED'|'DISCONNECTED';freshness:'FRESH'|'STALE'};
type State={riderName:string;rideStatus:'live'|'ended';startedAt:string;endedAt?:string;location?:Location;separationState:'unknown'|'separated'|'reunited';observerCredential?:string};
const api = import.meta.env.VITE_API_BASE_URL || window.location.origin;
function Center({location}:{location?:Location}) { const map=useMap(); useEffect(()=>{if(location)map.setView([location.latitude,location.longitude],15);},[location,map]); return null; }
function App(){ const [state,setState]=useState<State|null>(null); const [error,setError]=useState<string|null>(null); const [events,setEvents]=useState<string[]>([]); const token=useMemo(()=>window.location.hash.slice(1),[]);
 useEffect(()=>{if(!token){setError('This Guardian Portal link is unavailable.');return;} let cancelled=false; fetch(`${api}/api/guardian-portal/bootstrap`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}).then(async r=>r.ok?r.json():Promise.reject()).then((data:State)=>{if(cancelled)return; setState(data); history.replaceState(null,'',window.location.pathname);}).catch(()=>!cancelled&&setError('This Guardian Portal link is unavailable.')); return()=>{cancelled=true;};},[token]);
 useEffect(()=>{if(!state?.observerCredential||state.rideStatus!=='live')return; const socket=io(`${api}/guardian-portal`,{auth:{credential:state.observerCredential},transports:['websocket']}); socket.on('portal:location',(p:{latitude:number;longitude:number;lastUpdatedAt:number})=>setState(s=>s?{...s,location:{latitude:p.latitude,longitude:p.longitude,lastUpdatedAt:p.lastUpdatedAt,connectionState:'CONNECTED',freshness:'FRESH'}}:s)); socket.on('portal:presence',(p:Location)=>setState(s=>s?{...s,location:s.location?{...s.location,...p}:s.location}:s)); socket.on('portal:separated',()=>{setState(s=>s?{...s,separationState:'separated'}:s);setEvents(e=>['Rider separated from the group',...e]);}); socket.on('portal:reunited',()=>{setState(s=>s?{...s,separationState:'reunited'}:s);setEvents(e=>['Rider reunited with the group',...e]);}); socket.on('portal:sos',()=>setEvents(e=>['Emergency alert: rider triggered SOS',...e])); socket.on('portal:rideEnded',()=>setState(s=>s?{...s,rideStatus:'ended',observerCredential:undefined}:s)); socket.on('portal:revoked',()=>setError('This Guardian Portal link is no longer available.')); return()=>{socket.close();};},[state?.observerCredential,state?.rideStatus]);
 if(error)return <main><h1>Guardian Portal</h1><p>{error}</p></main>; if(!state)return <main><h1>Guardian Portal</h1><p>Loading live ride…</p></main>; const stale=!state.location||state.location.freshness==='STALE'; return <main><header><strong>GUARDIAN ANGEL</strong><span>Guardian Portal</span></header><h1>{state.riderName}</h1><p className={state.rideStatus==='ended'?'ended':stale?'stale':'live'}>{state.rideStatus==='ended'?'Ride ended':stale?'Temporarily offline — showing last known location':'Live ride'}</p><p>Ride started {new Date(state.startedAt).toLocaleString()}</p>{state.location?<MapContainer center={[state.location.latitude,state.location.longitude]} zoom={15}><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><Marker position={[state.location.latitude,state.location.longitude]}/><Center location={state.location}/></MapContainer>:<p>Location not available yet.</p>}<p>Last updated: {state.location?.lastUpdatedAt?new Date(state.location.lastUpdatedAt).toLocaleTimeString():'—'}</p>{state.separationState==='separated'?<p className="sos">Separation alert active</p>:null}<section><h2>Safety updates</h2>{events.length?events.map((e,i)=><p key={i}>{e}</p>):<p>No safety alerts.</p>}</section></main> }
createRoot(document.getElementById('root')!).render(<App/>);
