import React from 'react';
import renderer from 'react-test-renderer';
import FriendInvitePicker from '../FriendInvitePicker';
const response=(body:any, ok=true)=>({ok,json:async()=>body});
describe('FriendInvitePicker',()=>{
 beforeEach(()=>{global.fetch=jest.fn();});
 const mount=async()=>{let tree:renderer.ReactTestRenderer;await renderer.act(async()=>{tree=renderer.create(<FriendInvitePicker apiBaseUrl="https://api" authToken="token" roomId="room-uuid"/>);});return tree!;};
 it('shows loading then stable rows and supports multi-select/deselect',async()=>{let resolve:any;(global.fetch as jest.Mock).mockImplementationOnce(()=>new Promise(r=>resolve=r));const tree=await mount();await renderer.act(async()=>tree.root.findByProps({testID:'friend-invite-open'}).props.onPress());expect(tree.root.findByProps({testID:'friend-invite-loading'})).toBeTruthy();await renderer.act(async()=>resolve(response([{userId:'u',displayName:'Utsuk',username:'utsuk'},{userId:'r',displayName:'Radium',username:'radium'},{userId:'p',displayName:'Pratyush',username:'pratyush'}])));const u=tree.root.findByProps({testID:'friend-invite-row-u'}),r=tree.root.findByProps({testID:'friend-invite-row-r'});await renderer.act(async()=>{u.props.onPress();r.props.onPress();});expect(tree.root.findByProps({testID:'friend-invite-send'}).props.disabled).toBe(false);await renderer.act(async()=>u.props.onPress());expect(tree.root.findByProps({testID:'friend-invite-send'}).props.disabled).toBe(false);});
 it('uses authoritative room id and reports partial failures',async()=>{(global.fetch as jest.Mock).mockResolvedValueOnce(response([{userId:'u',displayName:'Utsuk'},{userId:'r',displayName:'Radium'}])).mockResolvedValueOnce(response({id:'one'})).mockResolvedValueOnce(response({error:'already pending'},false));const tree=await mount();await renderer.act(async()=>tree.root.findByProps({testID:'friend-invite-open'}).props.onPress());await renderer.act(async()=>{tree.root.findByProps({testID:'friend-invite-row-u'}).props.onPress();tree.root.findByProps({testID:'friend-invite-row-r'}).props.onPress();});await renderer.act(async()=>tree.root.findByProps({testID:'friend-invite-send'}).props.onPress());expect(global.fetch).toHaveBeenCalledWith('https://api/api/rooms/room-uuid/invitations',expect.objectContaining({body:JSON.stringify({invitee_user_id:'u'})}));expect(tree.root.findByProps({testID:'friend-invite-progress'}).props.children).toContain('could not');expect(tree.root.findByProps({testID:'friend-invite-send'}).props.disabled).toBe(true);});
});
